"""Added Device transport

Revision ID: 11e35a5ccf8f
Revises: 
Create Date: 2016-03-07 12:49:33.794048

"""

# revision identifiers, used by Alembic.
revision = '11e35a5ccf8f'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('transports', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'transports')
    ### end Alembic commands ###
