== REST API
U2F-val exposes its functionality over a REST API, which is made accessible to
authenticated clients. Clients are responsible for supplying a unique-per-user
persistent identifier for each user in its system in the form of a string no
more than 32 characters long. Usernames should only be used if they are
immutable. This user identification string is denoted userId in the API below.

=== JavaScript object type definitions
The following JavaScript objects are used when interacting with the REST API.
In addition to these, the RegisterRequest, RegisterResponse,
AuthenticationRequest, and AuthenticationResponse types from the U2F_V2
specification are used.

==== Error
Whenever an API call results in an error, an Error object is returned. The
errorCode determines the type of error, and the errorMessage gives a textual
description of the error. If applicable to the specific error, additional data
will be available in the errorData field.

[source,javascript]
----
dictionary Error {
  int errorCode;
  DOMString errorMessage;
  optional any errorData;
}
----

==== Device Descriptor
The DeviceDescriptor describes a registered U2F device. Each Device has a 
unique handle used to identify the device, as well as fields showing when the
device was registered (_created_) and last successfully used (_lastUsed_).
When available, metadata about the device will be present in the _metadata_
field, containing vendor and device information. This field will be omitted if
no such metadata exists. A dictionary of key-value _properties_ is available,
which can be used by the client to store arbitrary data. Lastly, a boolean
shows if the device has been marked as compromised. A compromised device cannot
be used for authentication. The system will mark a device as compromised if it
detects something which may indicate this, and a compromised device should be
replaced.

[source,javascript]
----
dictionary DeviceDescriptor {
  DOMString handle;
  DOMString created;
  DOMString lastUsed;
  DeviceMetadata metadata;
  dictionary properties;
  boolean compromised;
};
----

==== DeviceMetadata
The metadata provided in the DeviceDescriptor contains metadata about the
device vendor as well as the device itself. The two contained fields
(_VendorInfo_ and _Device_) are described link:missing.html[here].

[source,javascript]
----
dictionary DeviceMetadata {
  VendorInfo vendor;
  Device device;
};
----

==== RegisterRequestData
The RegisterRequestData contains the parameters needed to invoke the _register_
function of a FIDO client.

[source,javascript]
----
dictionary RegisterRequestData {
  AuthenticateRequest[] authenticateRequests;
  RegisterRequest[] registerRequests;
};
----

===== Members
*authenticateRequests* of type _array_ of _AuthenticateRequest_::
  A list of AuthenticateRequest dictionaries, one for each U2F device already
  registered by the user.
*registerRequests* of type _array_ of _RegisterRequest_::
  A list of RegisterRequest dictionaries, one for each protocol version that
  the server is willing to support.

==== RegisterResponseData
The RegisterResponseData contains the RegisterResponse returned by a successful
call to the _register_ function of a FIDO client, as well as any properties to
set, and names of properties to return, if the registration succeeds.

[source,javascript]
----
dictionary RegisterResponseData {
  RegisterResponse registerResponse;
  Dictionary properties;
};
----

===== Members
*registerResponse* of type _RegisterResponse_::
  The RegisterResponse to return to the server for validation.
*properties* of type _Dictionary_::
  A Dictionary of properties to set for the Device created upon successful
  validation of the RegisterResponse.

==== AuthenticationRequestData
The AuthenticationRequestData contains the parameters needed to invoke the
_authenticate_ function of a FIDO client.

[source,javascript]
----
dictionaty AuthenticateRequestData {
  AuthenticateRequest[] authenticateRequests;
}
----

===== Members
*authenticateRequests* of type _array_ of _AuthenticateRequest_::
  A list of AuthenticateRequest dictionaries, one for each previously
  registered U2F device for the user.

==== AuthenticationResponseData
The AuthenticationResponseData contains the AuthenticateResponse returned by a
successful call to the _authenticate_ function of a FIDO client, as well as any
properties to set, and names of properties to return, if the authentication
succeeds.

[source,javascript]
----
dictionary AuthenticateResponseData {
  AuthenticateResponse authenticateResponse;
  Dictionary properties;
};
----

===== Members
*authenticateResponse* of type _AuthenticateResponse_::
  The AuthenticateResponse to return to the server for validation.
*properties* of type _Dictionary_::
  A Dictionary of properties to set for the Device for which authentication is
  perfomed, if authentication succeeds.

=== HTTP resources

==== /:userId
*Example*::
_https://example.com/johndoe_

==== +HTTP GET+
Returns a list of device handles, with their properties, optionally filtered.

===== Query parameters
*filter*=[string[,string ...]]::
  (_optional_)
  When set, filter the properties returned by the names in the filter string.

===== Server response
_DeviceDescriptor[]_

==== +HTTP DELETE+
Deletes all data associated with the user.


==== /:userId/register
*Example*::
_https://example.com/johndoe/register_

==== +HTTP GET+
Initializes registration for the given user (all registered devices).

===== Server response
_RegisterRequestData_
  
==== +HTTP POST+

===== Query parameters
*filter*=[string[,string ...]]::
  (_optional_)
  When set, filter the properties returned by the names in the filter string.

Completes the registration, storing a new device associated with the user.

===== Client request body
_RegisterResponseData_

===== Server response
_DeviceDescriptor_


==== /:userId/authenticate
*Example*::
_https://example.com/johndoe/authenticate_

==== +HTTP GET+
Initializes authentication for the given user (all registered devices).

===== Server response
_AuthenticateRequestData_

==== +HTTP POST+
Completes the authentication, updating and returning properties for the device
which signed the challenge.

===== Query parameters
*filter*=[string[,string ...]]::
  (_optional_)
  When set, filter the properties returned by the names in the filter string.

===== Client request
_AuthenticateResponseData_

===== Server response
_DeviceDescriptor_


==== /:uid/:handle
*Example*::
_https://example.com/johndoe/0f0f0f0f0f...0f_

==== +HTTP GET+
Returns properties for the device, optionally filtered.

===== Query parameters
*filter*=[string[,string ...]]::
  (_optional_)
  When set, filter the properties returned by the names in the filter string.

===== Server Response
DeviceDescriptor

==== +HTTP POST+
Sets properties for the device, then returns the devices new properties,
optionally filtered.

===== Query parameters
*filter*=[string[,string ...]]::
  (_optional_)
  When set, filter the properties returned by the names in the filter string.

===== Client Request
_Dictionary_

===== Server Response
DeviceDescriptor

==== +HTTP DELETE+
Removes the device registration.

===== Server Response
HTTP 204 No Content
