#!/usr/bin/python
#    Copyright (C) 2014  Yubico AB
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


from u2fserver.model import Client
import os
import argparse


def parse_args():
    parser = argparse.ArgumentParser(
        description="Yubico U2F Validation Server",
        add_help=True
    )
    parser.add_argument('-c', '--config', help='specify an alternate '
                        'configuration file to use')
    subparsers = parser.add_subparsers(dest='command', help='sub-command help')

    client_parser = subparsers.add_parser('client', help='manage clients')
    client_parser.add_argument('action', help='the client action to perform')

    run_parser = subparsers.add_parser('run', help='run the server')
    run_parser.add_argument('-i', '--interface', nargs='?',
                            default='localhost', help='network interface to '
                            'bind to')
    run_parser.add_argument('-p', '--port', nargs='?', type=int, default=8080,
                            help='TCP port to bind to')

    return parser.parse_args()


def main():
    args = parse_args()

    if args.config:
        os.environ['U2FVAL_SETTINGS'] = args.config
    from u2fserver.config import settings

    print "Args:", args
    print "Settings:", settings


if __name__ == '__main__':
    main()
